### ISSUE TITLE
post problem

### ISSUE THREAD

**Issue by mugiwara123** [olleota/themes#183] opened 2015-02-01 03:10 UTC
please, i need help with the franz theme!

i have no idea what to do... i searched a while bit seems like i have no idea...
i reblogged few post with gifs and the gif pictures are not showing right.
it should have been 2 gifs aside and not every gif under a another... there is so much place and still,
they are showing under one another.

i hope someone can help me... i have really no idea what to change!

![unbenannt1](https://cloud.githubusercontent.com/assets/10792552/5990860/84c1ac7e-a9c7-11e4-858d-c3a9da672457.png)

**Comment by olleota** [comment] 2015-02-15 23:57
Duplicate of #180

**Closed** 2015-02-15 23:57 UTC
